apiVersion: v1
items:
- apiVersion: kafka.strimzi.io/v1
  kind: KafkaTopic
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"kafka.strimzi.io/v1","kind":"KafkaTopic","metadata":{"annotations":{},"labels":{"strimzi.io/cluster":"finsignal-kafka"},"name":"txn-events","namespace":"kafka"},"spec":{"config":{"retention.ms":604800000,"segment.bytes":1073741824},"partitions":3,"replicas":1}}
    creationTimestamp: "2026-06-03T19:17:09Z"
    finalizers:
    - strimzi.io/topic-operator
    generation: 1
    labels:
      strimzi.io/cluster: finsignal-kafka
    name: txn-events
    namespace: kafka
    resourceVersion: "6946"
    uid: 2113ca32-4ea8-4b82-bcc5-6c0a31778373
  spec:
    config:
      retention.ms: 604800000
      segment.bytes: 1073741824
    partitions: 3
    replicas: 1
  status:
    conditions:
    - lastTransitionTime: "2026-06-03T19:17:09.411788225Z"
      status: "True"
      type: Ready
    observedGeneration: 1
    topicId: mOuIQc78TlK6RTGN39AD4Q
    topicName: txn-events
kind: List
metadata:
  resourceVersion: ""
